### ISSUE TITLE
Is this project still under maintenance

### ISSUE THREAD

**Issue by Anivie** [gluonhq/gluonfx-gradle-plugin#174]
Oracle Graalvm has been released for a long time, but it is still not adapted, and the current plug-in does not work properly because the new Graal has changed the version release mechanism.

Error message:
```
Current GraalVM version (20.0.1) not supported.
Please upgrade to 22.1 or higher
```

**Comment by ctoabidmaqbool** [comment]
Every GluonFx-Plugin depends upon it's own GraalVM version. Please upgrade GraalVM to latest version.

**Comment by Anivie** [comment]
> Every GluonFx-Plugin depends upon it's own GraalVM version. Please upgrade GraalVM to latest version.

The latest Oracle Graal version number is 20

**Comment by ctoabidmaqbool** [comment]
https://github.com/gluonhq/graal/releases/tag/gluon-22.1.0.1-Final

Let see graalvm by gluon!

**Comment by jperedadnr** [comment]
Indeed, to use the GluonFX plugin, the GluonFX docs recommend the Gluon's GraalVM build https://github.com/gluonhq/graal/releases/tag/gluon-22.1.0.1-Final
which is mostly needed for the mobile target.
On desktop, the official GraalVM build can be used as well. However, there was an issue with the change in the GraalVM versioning system, which has just been fixed with https://github.com/gluonhq/substrate/pull/1222

This can be tested with the plugin 1.0.19
