### ISSUE TITLE
Clipboard.getSystemClipboard() does not work

### ISSUE THREAD

**Issue by websystemtechnology** [gluonhq/gluonfx-gradle-plugin#196]
On android using gluon plugin 1.0.22 and gluon attach version 4.0.21 Clipboard.getSystemClipboard() does not work.

`ClipboardContent content = new ClipboardContent();
content.put(DataFormat.PLAIN_TEXT, strTocopy);
content.putString(strTocopy);
Clipboard clipboard = Clipboard.getSystemClipboard();
clipboard.setContent(content);`

Note: on iOS everything is ok

**Comment by jperedadnr** [comment]
I don't see why that doesn't work.

I've tested it on desktop and Android, and it works fine: copying the text from a textField is added to the clipboard, and pasting it again to the same textField works, and also moving to another application and pasting it, works.

If something is not working for you, post a full test that reproduces the issue.

**Comment by websystemtechnology** [comment]
[project_test_gluon.zip](https://github.com/user-attachments/files/16561173/project_test_gluon.zip)

**Comment by websystemtechnology** [comment]
Attached is a test project, with the code we use. As said on desktop and iOS everything works correctly while on android if I copy a string (either by clicking from the textInputControl or by clicking on the copy button) and try to paste on another app (example notes or whatsapp) it does not work.

[project_test_gluon.zip](https://github.com/user-attachments/files/16561243/project_test_gluon.zip)

**Comment by jperedadnr** [comment]
There is an issue with Attach/Util. 

With a simple HelloGluon project, clipboard operations work as expected, but in your project you have many Attach services, and some of them require permissions.

The call in
https://github.com/gluonhq/attach/blob/master/modules/util/src/main/native/android/dalvik/Util.java#L50

```
    public Util(Activity activity) {
        Util.activity = activity;
        if (activity != null) { ... // clipboard support
...
```
stores the non-null Android MainActivity, usually after permission dialogs show up (that call `Util(null)`. However in your case, permissions are also called after that, and nullify Util.activity again, so clipboard operations bail out.

This will be fixed in Attach.

**Comment by jperedadnr** [comment]
You can test now with Attach 4.0.22-SNAPSHOT (adding the Sonatype repository)
